# Generated by Django 3.2.3 on 2021-05-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='check_weekly',
            field=models.BooleanField(default=False),
        ),
    ]
